configured_endpoints: 53
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/the-unnatural-group--llc%2Ftradesignals-3862b422118edd7ef2a5f773de9a315a0867c285449a7bbc0f352f44d0bc7cb3.yml
