configured_endpoints: 51
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/the-unnatural-group--llc%2Ftradesignals-b707f7a9ac7910736d391c7a603426c48386b6d7afd83a73f3206df509ae1c1c.yml
