configured_endpoints: 7
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/the-unnatural-group--llc%2Ftradesignals-206177d01d9a17064bc3528a97c1458fddc77a7b3a490eb6675de8588f29cd14.yml
