configured_endpoints: 51
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/the-unnatural-group--llc%2Ftradesignals-a1fe2a2b022bace9fdecfbccd8cb2a159dcbe29fbc449ce058ad9bbbdcf4c223.yml
