configured_endpoints: 2
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/the-unnatural-group--llc%2Ftradesignals-dc348fcd547ae04f710c9b1d01a8caa512b8416513843c0c001a307e7a62cc2c.yml
