configured_endpoints: 16
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/the-unnatural-group--llc%2Ftradesignals-195334615f03f62bf459d9cf0fb488e2fae0c9cf2209e81115cbe049e178541c.yml
