configured_endpoints: 31
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/the-unnatural-group--llc%2Ftradesignals-8774a250b773edfbb181263d36aeb470bf78ead31a82a6d5b6918deac992ccc3.yml
