configured_endpoints: 47
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/the-unnatural-group--llc%2Ftradesignals-ebd88d5fb0c17b7639fba63fe2253d2b3085fa5d09a2e6490baa94987fbf0d04.yml
